version: "3.8"

services:
  postgres_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
  app: # user-defined app
    depends_on:
      - postgres_db
    build: .
    expose:
      - ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./src:/app/src
    command: npm run dev
    environment:
      - DB_URL=postgres://root:root@postgres_db:5432/root
      - OPENAI_API_KEY=${OPENAI_API_KEY?error}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - PORT=${API_PORT}
  studio: # a next-js frontend we provide as a docker image
    image: studio:latest
    ports:
      - 3000:3000
    environment:
      - API_URL=http://app:${API_PORT}
      - SERVICE_KEY=abc123

  jaeger: # tracing service
    image: jaegertracing/all-in-one:1.56
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SPAN_STORAGE_TYPE=cassandra
      - CASSANDRA_SERVERS=cassandra
    ports:
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  cassandra: # storage for jaeger
    image: cassandra:4.0
